### ISSUE TITLE
Einrichtung ausschließlicher lokaler Betrieb

### ISSUE THREAD

**Issue by andyb87** [GertzGutscheRuemenapp/bule_datentool#371]
moin,

Ich versuche gerade das Tool lokal auf meinem Linux Rechner laufen zu lassen und nutze dazu die option für den lokalen Betrieb (Installationshandbuch Seite 6 unten)

Leider kriege ich es nicht hin den Stack zum laufen zu bringen, ich hab penibel die Anleitung befolgt.
Im Browser kriege ich nur eine weise Seite und den folgenden Inhalt:
![image](https://user-images.githubusercontent.com/63102372/232343208-ec4f7fad-355f-47c6-b40e-fe4fbe7652ab.png)

Ich würde mich sehr freuen wenn Ihr mir weiter helfen könntet :)

Vielen Dank vorab und beste Grüße
Andy

**Comment by ChrFr** [comment]
Schwierig da eine Ferndiagnose zu machen. Läuft die Anwendung im Docker-Container? Sind die .js- und .css-Ressourcen erreichbar (mal testweise auf die Links klicken)? Kannst du mir bitte das Netzwerk-Log zukommen lassen (hier als Screenshot oder gern an meine E-Mail)?

**Comment by andyb87** [comment]
moin nochmal,

Danke für die schnelle Rückmeldung.
Zu deinen Fragen:

1. Das Tool läuft als docker-compose stack, ich bin genau nach der Anleitung im ordner "dist" vorgegangen bzw. nach dem Installationshandbuch für die lokale developer Instanz
2. Ich hab gerade in das Netzwerk-Log meines Browsers geguckt und tatsächlich werden die .js und die .css dateien geblockt (ich hab keine blocker aktiv und habs auch mit einem cleanen browser getastet) und kann sie auch nicht aufrufen wenn ich die als link versuche zu laden
Anbei der screenshot dazu:
![image](https://user-images.githubusercontent.com/63102372/232443758-0ef83423-1af7-488b-87cd-bc3ade241649.png)

woran kann das liegen?

Vielen Dank nochmal und beste Grüße
Andy

**Comment by ChrFr** [comment]
Das ist jetzt keine Lösung, aber hast du es mal mit einem anderen Browser probiert?
Ich kann mit dem NS_ERROR_CORRUPTED_CONTENT Fehler gerade nichts anfangen und weiß nicht, ob das ein Firefox-spezifisches Problem ist. Muss ich mal lokal bei mir ausprobieren.

**Comment by andyb87** [comment]
Hab das bisher in Firefox und Chrome probiert, hier ist der log aus Chrome:
![image](https://user-images.githubusercontent.com/63102372/232450258-51a35087-1349-4a64-97ef-c3f2dea78344.png)

**Comment by ChrFr** [comment]
Danke für die Rückmeldung. Ich bekomme das gleiche Problem lokal bei mir. Django weigert sich im Container die Ressourcen richtig zu routen und nach draußen zu geben. Mal schauen, wie ich das beheben kann.

**Comment by ChrFr** [comment]
Um das Programm lokal ohne Domain zum Laufen zu bekommen, muss die docker-compose.yml angepasst werden:
bitte ersetze die command des _web_-Services durch 
**command**: _bash -c "cd /datentool/angular-frontend && npm i && ng build --stats-json --configuration development && cd /datentool/ && python manage.py migrate --run-syncdb && (python manage.py qcluster &) && python manage.py runserver 0.0.0.0:8000"_

Wenn man das allerdings so laufen lässt (ohne _daphne_, letzter Teil des commands), kann es aus Erfahrung manchmal bei größeren Berechnungen zum Absturz oder sogar Deadlock kommen, wenn man zu viele Anfragen ans Backend gleichzeitig abschickt (durch wildes Rumgeklicke im Frontend). Dafür kann Django aber so selbst die static-Files ohne irgendwelche zusätzlichen Services ausliefern. Alternativ müsste man im Container noch NGINX laufen lassen und damit das static-Files-Verzeichnis über einen Port nach draußen mappen.

Die Environmentvariable DJANGO_SETTINGS_MODULE muss in der docker-compose.yml auf _datentool.settings_dev_ gesetzt werden (hast du vermutlich schon)

Außerdem muss der Service blöderweise im Moment im Development-Modus auf Port **8000** nach außen laufen (EXT_PORT-Variable), da ich das Frontend im Development (der "_--configuration development_ "-Teil bei ng build) im Code fest auf den Port gesetzt habe. Ich werde probieren, ob ich das an der Stelle im Code aus den Umgebungsvariablen auslesen kann.

Ich weiß noch nicht, wie wir diese "Ausprobierversion" ausliefern. Entweder pushe ich eine angepasste docker-compose auf github oder ich pushe ein extra Image mit einem entsprechenden Tag.
